---
title: "JTZ_data_simulation_example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{JTZ_data_simulation_example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
library(JTZ)
library(pracma)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

**Authors**: Liang Jiang, Haihan Tang, Yichong Zhang

**Date**: 20220807

## Parameter specification
```{r}
tic()
set.seed(1)
iMonte <- 1000  # Monte Carlo sizes
dgptype <- 1 # 1,2,3 (see paper for details)
n <- 200 # sample size
g <- 4 # number of strata. we set g = 4 in the paper
pi <-  0.5 # targeted assignment probability
iPert <- 0 # scalar. iPert = 0 means size. Otherwise means power: iPert is the perturbation of false null
iq <- 0.05 # size of hypothesis testing. We set iq = 0.05
iridge <- 0.001 # scalar. The penalization parameter in ridge regression
```

## Simulate the LATE tau
```{r}
# only run once
#truevalue_result <- TrueValue(dgptype = dgptype, vIdx = 1:4, n = 10000, g = g, pi = pi)
#tau <- truevalue_result[["tau"]]
#print("Finish simulating true tau.")

#True tau ! 
vtau <- c(0.9213287, 0.9226964, 0.9213111, 0.9206209)
```

## Monte Carlo Experiment
```{r, message=FALSE, warning=FALSE, results='hide', cache=TRUE}
# If a value exists, cols are (1)NA (2)LP (3)LG (4)F (5)NP (6)lasso (7)2SLS (8)R
# 1-SRS
mtauhat_d1 <- NaN*ones(iMonte, 8)
msighat_d1 <- NaN*ones(iMonte, 8)
mstat_d1   <- NaN*ones(iMonte, 8)
mdeci_d1   <- NaN*ones(iMonte, 8)

# 2-WEI
mtauhat_d2 <- NaN*ones(iMonte, 8)
msighat_d2 <- NaN*ones(iMonte, 8)
mstat_d2   <- NaN*ones(iMonte, 8)
mdeci_d2   <- NaN*ones(iMonte, 8)

# 3-BCD
mtauhat_d3 <- NaN*ones(iMonte, 8)
msighat_d3 <- NaN*ones(iMonte, 8)
mstat_d3   <- NaN*ones(iMonte, 8)
mdeci_d3   <- NaN*ones(iMonte, 8)

# 4-SBR
mtauhat_d4 <- NaN*ones(iMonte, 8)
msighat_d4 <- NaN*ones(iMonte, 8)
mstat_d4   <- NaN*ones(iMonte, 8)
mdeci_d4   <- NaN*ones(iMonte, 8)


for (i in 1:iMonte) {
  print("1-SRS")
  # 1-SRS
  result_srs <- tryCatch({Output(ii = i, tau = vtau[1], dgptype = dgptype, rndflag = 1,
                  n = n, g = g, pi = pi, iPert = iPert, iq = iq, iridge = iridge)},
           error = function(e) {list(vtauhat = NA, vsighat = NA,
                                                    vstat = NA, vdeci = NA)})

  vtauhat_d1 <- result_srs[["vtauhat"]]
  vsighat_d1 <- result_srs[["vsighat"]]
  vstat_d1   <- result_srs[["vstat"]]
  vdeci_d1   <- result_srs[["vdeci"]]

  mtauhat_d1[i,] <- vtauhat_d1
  msighat_d1[i,] <- vsighat_d1
  mstat_d1[i,]   <- vstat_d1
  mdeci_d1[i,]   <- vdeci_d1

  # 2-WEI
  print("2-WEI")
  result_wei <- tryCatch({Output(ii = i, tau = vtau[2], dgptype = dgptype, rndflag = 2,
                  n = n, g = g, pi = pi, iPert = iPert, iq = iq, iridge = iridge)},
           error = function(e) {list(vtauhat = NA, vsighat = NA,
                                            vstat = NA, vdeci = NA)})
  vtauhat_d2 <- result_wei[["vtauhat"]]
  vsighat_d2 <- result_wei[["vsighat"]]
  vstat_d2   <- result_wei[["vstat"]]
  vdeci_d2   <- result_wei[["vdeci"]]

  mtauhat_d2[i,] <- vtauhat_d2
  msighat_d2[i,] <- vsighat_d2
  mstat_d2[i,]   <- vstat_d2
  mdeci_d2[i,]   <- vdeci_d2

  # 3-BCD
  print("3-BCD")
  result_bcd <- tryCatch({Output(ii = i, tau = vtau[3], dgptype = dgptype, rndflag = 3,
                  n = n, g = g, pi = pi, iPert = iPert, iq = iq, iridge = iridge)},
           error = function(e) {list(vtauhat = NA, vsighat = NA,
                                                    vstat = NA, vdeci = NA)})


  vtauhat_d3 <- result_bcd[["vtauhat"]]
  vsighat_d3 <- result_bcd[["vsighat"]]
  vstat_d3   <- result_bcd[["vstat"]]
  vdeci_d3   <- result_bcd[["vdeci"]]

  mtauhat_d3[i,] <- vtauhat_d3
  msighat_d3[i,] <- vsighat_d3
  mstat_d3[i,]   <- vstat_d3
  mdeci_d3[i,]   <- vdeci_d3

  # 4-SBR
  print("4-SBR")
  result_sbr <- tryCatch({Output(ii = i, tau = vtau[4], dgptype = dgptype, rndflag = 4,
                  n = n, g = g, pi = pi, iPert = iPert, iq = iq, iridge = iridge)},
           error = function(e) {list(vtauhat = NA, vsighat = NA,
                                                    vstat = NA, vdeci = NA)})

  vtauhat_d4 <- result_srs[["vtauhat"]]
  vsighat_d4 <- result_srs[["vsighat"]]
  vstat_d4   <- result_srs[["vstat"]]
  vdeci_d4   <- result_srs[["vdeci"]]

  mtauhat_d4[i,] <- vtauhat_d4
  msighat_d4[i,] <- vsighat_d4
  mstat_d4[i,]   <- vstat_d4
  mdeci_d4[i,]   <- vdeci_d4
}
```

## Evaluation
```{r}
vProb_d1 <- colMeans(mdeci_d1, na.rm = TRUE) # 1x8. size or power depending on the context.
vProb_d2 <- colMeans(mdeci_d2, na.rm = TRUE)
vProb_d3 <- colMeans(mdeci_d3, na.rm = TRUE)
vProb_d4 <- colMeans(mdeci_d4, na.rm = TRUE)
mProd <- t(rbind(vProb_d1,vProb_d2,vProb_d3,vProb_d4))

mProd

toc()
```
